// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAppOOP.db;

#nullable disable

namespace RestaurantAppOOP.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantAppOOP.models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Menu__3213E83F23E41A07");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("RestaurantAppOOP.models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("date")
                        .HasColumnName("dateOrder");

                    b.Property<int>("IdWaiter")
                        .HasColumnType("int")
                        .HasColumnName("idWaiter");

                    b.Property<int>("NumberOfTable")
                        .HasColumnType("int")
                        .HasColumnName("numberOfTable");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3213E83F8FBF43D6");

                    b.HasIndex("IdWaiter");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantAppOOP.models.OrderedDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdMenu")
                        .HasColumnType("int")
                        .HasColumnName("idMenu");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("idOrder");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("PK__OrderedD__3213E83F5BBA48BA");

                    b.HasIndex("IdMenu");

                    b.HasIndex("IdOrder");

                    b.ToTable("OrderedDish", (string)null);
                });

            modelBuilder.Entity("RestaurantAppOOP.models.Waiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameWaiter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nameWaiter");

                    b.HasKey("Id")
                        .HasName("PK__Waiters__3213E83F495371ED");

                    b.ToTable("Waiters");
                });

            modelBuilder.Entity("RestaurantAppOOP.models.Order", b =>
                {
                    b.HasOne("RestaurantAppOOP.models.Waiter", "IdWaiterNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdWaiter")
                        .IsRequired()
                        .HasConstraintName("FK_Waiter");

                    b.Navigation("IdWaiterNavigation");
                });

            modelBuilder.Entity("RestaurantAppOOP.models.OrderedDish", b =>
                {
                    b.HasOne("RestaurantAppOOP.models.Menu", "IdMenuNavigation")
                        .WithMany("OrderedDishes")
                        .HasForeignKey("IdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Menu");

                    b.HasOne("RestaurantAppOOP.models.Order", "IdOrderNavigation")
                        .WithMany("OrderedDishes")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order");

                    b.Navigation("IdMenuNavigation");

                    b.Navigation("IdOrderNavigation");
                });

            modelBuilder.Entity("RestaurantAppOOP.models.Menu", b =>
                {
                    b.Navigation("OrderedDishes");
                });

            modelBuilder.Entity("RestaurantAppOOP.models.Order", b =>
                {
                    b.Navigation("OrderedDishes");
                });

            modelBuilder.Entity("RestaurantAppOOP.models.Waiter", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
